# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'QA Interview Mobile App' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QA Interview Mobile App

  # ReactiveX
  pod 'RxSwift'
  pod 'RxCocoa'

  # UI Management
  pod 'TPKeyboardAvoiding'

  # Alerts & Animation
  pod 'KVNProgress'

  # Image
  pod 'Kingfisher'

  # Localization
  pod 'PolyglotLocalization'

  # Util
  pod 'SwiftLint'

end